version: "3.4"

networks:
  web:
    external: true

services:
  streamlit-app:
    container_name: appprueba2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STREAMLIT_SERVER_PORT=8501
    expose:
      - "8501"
    networks:
      - web
    labels:
      # Traefik
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:appprueba2.seoclick.co"
      traefik.port: '8501'
      traefik.docker.network: 'web'
      traefik.frontend.headers.SSLRedirect: 'true'
    volumes:
      - .:/app